### ISSUE TITLE
Revisit dashboard calculation page

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#148]
For whatever reason, the Cuyahoga dashboard says that the 
Number of Cuyahoga County properties scanned for mortgage information: 347483 (61%)

but 

the Number of Cuyahoga County properties with mortgage information: 0 ( 0%)

(Though if I click on Cuyahoga in the database, it says we have 569,776 properties.)

**Comment by walinchus** [comment]
So I checked the dashboard, it says: 

Number of Warren County properties scanned for mortgage information: 70781 (70%)
Number of Warren County properties with mortgage information: 70692 ( 70%)
Total number of Warren County properties: 100459 

Number of Cuyahoga County properties scanned for mortgage information: 347483 (61%)
Number of Cuyahoga County properties with mortgage information: 0 ( 0%)
Total number of Cuyahoga County properties: 569776

Number of Franklin County properties scanned for mortgage information: 19514 (5%)
Number of Franklin County properties with mortgage information: 0 ( 0%)
Total number of Franklin County properties: 432026 

I went to the Django admin and tried to sort by mortgage amount. In Warren County, it would do so. In both Franklin and Cuyahoga counties, it would not, the mortgage amount is blank. 

I am going to hold off on Franklin and Cuyahoga counties then until we can get a mortgage amount. 

Also, for the Warren properties, I'm worried there are some with no mortgage amount not because there is no mortgage amount but because we haven't scraped it. To be on the safe side I am running the Warren one again.

**Comment by walinchus** [comment]
(Because it will now say when it was last scraped.)

**Comment by walinchus** [comment]
Though I'm guessing there's a way to just scrape that 30 percent with the please_parse_these_items variable?

**Comment by ludstuen90** [comment]
Cuyahoga appearing as zero percent mortgage: This number accurately
represents the data. For Cuyahoga county, we found the mortgage amount was
stored in PDFs and we couldn't download the amounts. Instead, we decided to
store transfer info

https://github.com/ludstuen90/property_project_ohio/wiki/What-can-be-scraped%3F


Franklin... The mortgage amounts are stored on a separate site, and I need
to write the scraper to download that information. Until that happens, I
would recommend running the  Franklin scraper - we can run the separate
mortgage one when it's ready.

This issue represents making that separate scraper

https://github.com/ludstuen90/property_project_ohio/issues/143

**Comment by walinchus** [comment]
Ah ok that explains a lot. A few questions:

Can we download the PDF anyway, get into the plain text with a PDF-to-text
function, and maybe use regex to get the mortgage amount? Not an elegant
solution, I know, but I've used the converter function in Python before.
(To see if I could get the redacted part of a PDF. Nope, that part is
redacted in the plain text, too! I was hoping it would just be like a black
box over it.)

Someone on the NICAR listerv suggested this, and I think it's a good idea-
he actually put in a variable to the scraper, so sometimes it's every time,
and sometimes it's every few seconds and whatnot. Maybe we can try that? If
not- I calculated this- it will take us a year to scrape the site. Aye.





Lucia Walinchus
*Executive Director*


Phone: 646-397-7761
Email: Lucia@EyeOnOhio.com
Twitter: @SoSaysLucia
*Want to get investigative news first? Sign up for our free newsletter
<http://EyeOnOhio.com>! (Homepage bottom left)*

**Comment by ludstuen90** [comment]
I like that idea! I say let's give it a try. The priority now would be to
finish mortgage for Franklin County, and then loop back to Cuyahoga?

No more trips planned now for a while, so we should be able to make some
good progress in the coming weeks, I think!

The delay in scraping Cuyahoga otherwise would be because people would be
trying to do the work manually, no?

**Comment by walinchus** [comment]
Yes. Ok great. Franklin is at about 124,000 so far.

Well in Cuyahoga the good news is I called them up and explained I was a
reporter and got reinstated. The bad news is they now want us to tone down
our requests to every one minute. Apparently they had been previously sued (see
the depo here
<http://www.sconet.state.oh.us/pdf_viewer/pdf_viewer.aspx?pdf=687295.pdf>)
and are very skittish about the whole thing. So I have reached out to the
county asking them to just give us, as journalists, the info, as smaller
counties such as Athens have done. And we will keep scraping at 1/min
(though that will take a year by my calculations). Though I like the
thought of randomly changing the requests to scrape between a second and a
minute to see if that will work. Or maybe scraping with multiple computers?
Though then we'd have to combine databases later.



Lucia Walinchus
*Executive Director*


Phone: 646-397-7761
Email: Lucia@EyeOnOhio.com
Twitter: @SoSaysLucia
*Want to get investigative news first? Sign up for our free newsletter
<http://EyeOnOhio.com>! (Homepage bottom left)*
