### ISSUE TITLE
Cuyahoga mortgage amount not showing up.

### ISSUE THREAD

**Issue by walinchus** [ludstuen90/property_project_ohio#165]
Hmm for some reason the mortgage amount is not showing up for Cuyahoga. Even though the rest of the info like date_sold and date_of_mortgage does.

**Comment by ludstuen90** [comment]
Ah yes, it looks like this information is only stored in PDFs, which isn't easily scraped, as mentioned in the wiki: https://github.com/ludstuen90/property_project_ohio/wiki/What-can-be-scraped%3F

I could dedicate some time to trying to scrape this, but I think it would be high effort, low payoff. 

This weekend, I had thought about starting a scraper for Montgomery County, since the CSV scrapers we wrote weren't as effective as we would have hoped. 

I'll start on that this weekend, but if that doesn't sound OK, let me know!

**Comment by walinchus** [comment]
Actually the mortgage amount can be scraped, but you have to click twice to get there. And there’s not always consistent about adding in an amount. But hold on a second I will show you.

**Comment by walinchus** [comment]
So for example, for this parcel number: 007-12-041

When you search for it, you get a bunch of records: 

![image](https://user-images.githubusercontent.com/25959269/62429130-a8a3a980-b6d8-11e9-8c72-e073da71cb47.png)

And then looking at the most recent mortgage: 

At the top it has "[View image]" but then under amount that is the real amount of the mortgage, not in PDF: 

![image](https://user-images.githubusercontent.com/25959269/62429143-cffa7680-b6d8-11e9-906c-a1bb09a44911.png)

**Comment by walinchus** [comment]
I talked to the Cuyahoga administration, and they said they didn't always put a number in there for the mortgage, so quite a few are 0, but I'd like to get what we can.

**Comment by ludstuen90** [comment]
@walinchus  Ah yes, I see a few things happening: 
* This scraper was set up when I thought we didn't want to save a mortgage IF the mortgage was not that of the current owner. Therefore, we were discarding mortgage dates if it wasn't from the current owner. (Have since learned that the mortgage date + amount is enough to piece together information we want
* We did not have scraper code to advance to the next page to try for a mortgage amount. Will write that now.

**Comment by walinchus** [comment]
Awesome thanks

**Comment by ludstuen90** [comment]
Sent email to Lucia, update to scraper programmed.
