### ISSUE TITLE
Add scraping for Cuyahoga County

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#24]
Add ability to scrape property data. Test solution.

The following items do not appear to be available for Cuyahoga County: 
- [ ] Mortgage amount (only appears to be stored in PDFs, which aren't easily scraped) 
- [ ]  CAUV property
- [ ]  Next year's taxes (2018, as of December, 2018) 

The following items seem to be intermittently available (available on some properties, but not all... we scrape when possible): 
- [x]  Legal acres 

Not sure yet how we can scrape these items (both for Cuyahoga county and Warren): 
- [x]  Tax Liens

**Comment by ludstuen90** [comment]
Built in xpath technology doesn't scrape existing site very well. Working now with Beautiful Soup, and although documentation says it's slower than xpath, it seems to be working very well.

**Comment by walinchus** [comment]
Sure. So a deed is technically your actual title to the property. It's the piece of paper that shows you own the property. You would want to record that deed, so that essentially the government knows you have rights to the property. And that way no one else can claim it if you do so first. 

So how it usually works is, you buy the property, sign all the paperwork at the closing, send the completed documents to the government, and they record the deed and send you back your official copy a few weeks later. 

You don't necessarily need to buy it, though. You could inherit the property, or if you've bought an LLC, then you could just hand over the deed as part of the sale of the _business_, which under Ohio law isn't technically a sale of the property. Usually in that case, though, the deed would still be owned by the business, but they may or may not change their name. 

So I would called it maybe "Date_Sale_Recorded".

When you see "MORT" that's a mortgage on the property. So that will be important for our purposes because we want to know if there's a large mortgage on a property that hasn't been sold. So in that Athens example, the property was on the books for $12 million because it hadn't been sold in like 20 years. But there was a bank willing to lend $49.5 million to purchase the property. So that's a red flag.  

"FIX" is just a fixture lien. So usually anything physically attached to a building is owned by whoever owns the building. But if you lend money for large equipment, you want to rip that out and at least salvage some value if there's a foreclosure. 

"RELS" is just a release of the lien. It means the mortgage has been paid off.

"DESH"  looks like it's a sherriff's deed-- in other words, there was a foreclosure. 

Looks like "DECT" is a certificate of transfer. So here the property passed through probate court and someone inherited it.

**Comment by ludstuen90** [comment]
@walinchus Awesome, thanks for this clarification! It looks like for the purposes of our scraper then, we'll be set to understand that the `date_sold` field is really a representation of the most recent deed recorded by the county ... and we'll understand that there could be a variety of reasons why a property has changed hands, which might not explicitly involve a sale. 

I think even that will provide valuable information, no? 

And awesome, this is good information. In a future iteration we could also track foreclosures/RELS for some other stories, I bet!

**Comment by ludstuen90** [comment]
Note to self: switching scraping to this site, provides much more information than earlier site noted for cuyahoga county https://myplace.cuyahogacounty.us/MTAxMzcwMDE=?city=OTk=&searchBy=UGFyY2Vs&dataRequested=R2VuZXJhbCBJbmZvcm1hdGlvbg==

**Comment by ludstuen90** [comment]
@walinchus Looks like Cuyahoga County's Fiscal Office website doesn't record the mortgage amount in a scrapable format -- but we can get mortgage and deed dates recorded. 

The actual dates of transfer are available on the MyPlace Cuyahoga website, which we scrape most of the content from, but I figure it makes sense to be consistent with Warren County and record the date transfer recorded.

**Comment by ludstuen90** [comment]
In addition to the aforementioned deed types, we will record 'DEAF' - Deed Affidavits as 'last date of transfer' for the property.

**Comment by ludstuen90** [comment]
@walinchus As we approach Thursday, I updated the description of this issue with the status of Cuyahoga county. 

I'll keep looking for other ways we can get the data listed as not available!

**Comment by ludstuen90** [comment]
Closing issue as we scrape all the info we need; school district info remains, but marked as 'nice to have,' not MVP.
